CREATE TABLE messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id         BIGINT NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    sender_id       BIGINT NOT NULL REFERENCES users (id),
    content         VARCHAR(4000) NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_messages_room_id_created_at ON messages (room_id, created_at);
CREATE INDEX idx_messages_room_id_id ON messages (room_id, id);
