CREATE TABLE stored_files (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id   BIGINT NOT NULL REFERENCES users (id),
    original_name   VARCHAR(255) NOT NULL,
    content_type    VARCHAR(100) NOT NULL,
    size_bytes      BIGINT NOT NULL,
    storage_key     VARCHAR(500) NOT NULL,
    purpose         VARCHAR(20) NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_stored_files_storage_key UNIQUE (storage_key),
    CONSTRAINT chk_stored_files_purpose CHECK (purpose IN ('AVATAR', 'MESSAGE'))
);

CREATE INDEX idx_stored_files_owner_user_id ON stored_files (owner_user_id);
