ALTER TABLE users
    ADD COLUMN avatar_file_id BIGINT REFERENCES stored_files (id) ON DELETE SET NULL;

ALTER TABLE messages
    ADD COLUMN message_type VARCHAR(20) NOT NULL DEFAULT 'TEXT';

ALTER TABLE messages
    ALTER COLUMN content DROP NOT NULL;

UPDATE messages
SET content = ''
WHERE content IS NULL;

ALTER TABLE messages
    ADD CONSTRAINT chk_messages_message_type CHECK (message_type IN ('TEXT', 'IMAGE_ALBUM'));

CREATE TABLE message_attachments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id  BIGINT NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
    file_id     BIGINT NOT NULL REFERENCES stored_files (id),
    sort_order  INT NOT NULL,
    CONSTRAINT uk_message_attachments_file_id UNIQUE (file_id)
);

CREATE INDEX idx_message_attachments_message_id ON message_attachments (message_id);
